### ISSUE TITLE
关于自制数据集

### ISSUE THREAD

**Issue by xiaofeiso** [Hymwgk/simulate_dataset_generation#1]
大佬，你好，请问下，我尝试用solidworks制作3维模型，然后转成stl，又生成obj,pcd，sdf文件，然后按照ycb数据集的google_512k的方式摆放的，但是运行
python sample_grasps_for_meshes.py  --gripper  panda --mode b  --rounds 1 --process_n 60  --grasp_n 200  
我发现生成路径下是空的，
运行
python sample_grasps_for_meshes.py  --gripper  panda --mode p  
然后出现：
There is no original grasp files!
你知道可能的原因吗。

**Comment by Hymwgk** [comment]
你好，其实我只是个菜鸟...  这个原因其实蛮多的，代码写的有点早了，具体的问题我也不好直接看出来，可能的问题有：

- 采样时间不够 （非常耗时，需要一两天）
- 模型尺寸不合适，夹爪夹不起来，找不到有效采样
- 需要完全确保路径正确
- 等等

There is no original grasp files!  只是说没有读取到保存的采候选抓取，具体问题一定是在采样部分；
我建议   最好是一步步调试过去；其中采样器部分，用的是Dex-net里面的，也可以仔细理解下采样器部分，问题也可能出在那里

**Comment by xiaofeiso** [comment]
谢谢大佬，又试了下可以跑了，但是看到终端一直在跑，我数据集里面就一个零件，请问下这个如果采样的话要大概多久？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月15日(周二) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hymwgk/simulate_dataset_generation] 关于自制数据集 (Issue #1)




 
你好，其实我只是个菜鸟...  这个原因其实蛮多的，代码写的有点早了，具体的问题我也不好直接看出来，可能的问题有：
  
采样时间不够 （非常耗时，需要一两天）
 
模型尺寸不合适，夹爪夹不起来，找不到有效采样
 
需要完全确保路径正确
 
等等
  
There is no original grasp files!  只是说没有读取到保存的采候选抓取，具体问题一定是在采样部分；
 我建议   最好是一步步调试过去；其中采样器部分，用的是Dex-net里面的，也可以仔细理解下采样器部分，问题也可能出在那里

**Comment by xiaofeiso** [comment]
我跑了10分钟还没结束，终端一直是跑的这个结果，请问下这个情况是正常的吗？
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
Object: GoodGrasp:[0. 0. 0.]
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
Object: GoodGrasp:[0. 0. 0.]
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 2.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
Object: GoodGrasp:[0. 0. 0.]
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:Num surface: 2
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 3.
INFO:dexnet.grasping.grasp_sampler:0/100 grasps found after iteration 1.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Found 0 grasps.
INFO:dexnet.grasping.grasp_sampler:Num surface: 2

**Comment by Hymwgk** [comment]
不太正常，虽然找到候选抓取采样要很久   但是   这个采样结果一直都是0   应该是有问题的， 你可以拿着原本数据集里的有的东西试一下先

**Comment by xiaofeiso** [comment]
会不会是点云的问题，我的点云比较密集，而且用solidwork建模做的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月16日(周三) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hymwgk/simulate_dataset_generation] 关于自制数据集 (Issue #1)




 
不太正常，虽然找到候选抓取采样要很久   但是   这个采样结果一直都是0   应该是有问题的， 你可以拿着原本数据集里的有的东西试一下先

**Comment by Hymwgk** [comment]
因为antipodal采样是随机的，mesh太密集确实可能会导致采集次数过多，你可以试试降低下密度（和sw建模没有关系）   我建议还是先试试别人的模型采样怎么样   然后多调试看看

**Comment by xiaofeiso** [comment]
现在跑的和原数据集类似了，我的情况是sdf文件使用其他程序转的，所以可能有点问题，不过用官方read_file_sdf就好了

**Comment by xiaofeiso** [comment]
你好，大佬，问一下采样两三天是指一个零件采样的时间吗？我采样原数据集和自己制作的数据集的时候，跑了一些就在这个界面不动了，代码也没停止，这是配置的问题，还是要采样结束后才会停止吗？
Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaofeisong/anaconda3/envs/pointnetgpd/bin/imageformats" ...
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"

**Comment by Hymwgk** [comment]
ycb数据集合  全部跑下来大约一天多吧； 具体的bug问题可能需要自己查一下哈

**Comment by xiaofeiso** [comment]
> ycb数据集合 全部跑下来大约一天多吧； 具体的bug问题可能需要自己查一下哈
大佬，你在训练pointnetgpd的时候出现过这个吗？
raceback (most recent call last):
  File "main_1v.py", line 278, in <module>
    main()
  File "main_1v.py", line 255, in main
    acc_train = train(model, train_loader, epoch)
  File "main_1v.py", line 122, in train
    for batch_idx, (data, target) in enumerate(loader):
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xiaofeisong/anaconda3/envs/pointnetgpd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/f/code/PointNetGPD/PointNetGPD/model/dataset.py", line 789, in __getitem__
    fl_pc = np.array(self.d_pc[obj_pc])
KeyError: '004_sugar_box'

**Comment by Hymwgk** [comment]
不好意思   时间太久了   这种具体的报错已经记不清楚了

**Comment by xiaofeiso** [comment]
你好，请问下训练Ycb数据集能不能只训练一部分呢？我训练完成第一轮后出现keyerror:037_scissor，但是我并没有下载这个物品的mesh，如何解决呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hymwgk/simulate_dataset_generation] 关于自制数据集 (Issue #1)




 
不好意思   时间太久了   这种具体的报错已经记不清楚了

**Comment by xiaofeiso** [comment]
请问下bg_funnel_part.stl是自己做的吗？是不是桌子之类的场景文件。

**Comment by Hymwgk** [comment]
> 
是的   就是把桌子围起来  防止东西掉下去

**Comment by Hymwgk** [comment]
keyerror:037_scissor  关于这个  实在不好意思   我是真的记不得了    好像是代码里有个字典？列表？之类的，可能需要根据自己有的东西改下？   是在记不得了    可以看看我的一些备注有没有    不过确实挺乱的

**Comment by xiaofeiso** [comment]
你好，大佬，我问个有关pointnetgpd的问题，我就是在尝试把pointnet替换为pointnet2,但是发现训练时间变得特别的长，请问下grasp_amount_per_file=6500这个数字建议改小吗？我的电脑不行，太大的数字要训练很久。

**Comment by Hymwgk** [comment]
可以适当改小吧    建议可以去看下 [gpg  ](https://github.com/atenpas/gpg)  是用c++写的  ，效率很高   当时如果时间再多些  我就用这个采样了
